# Generated by Django 5.2 on 2025-06-01 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDocenteCuatrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_general', models.FloatField()),
                ('ciclo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cicloperiodo', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('ingreso_h', models.IntegerField(default=0)),
                ('ingreso_m', models.IntegerField(default=0)),
                ('egresados_total', models.IntegerField(default=0)),
                ('titulados_total', models.IntegerField(default=0)),
                ('registrados_dgp_total', models.IntegerField(default=0)),
                ('egresados_trabajan', models.IntegerField(default=0)),
                ('egresados_trabajan_area', models.IntegerField(default=0)),
                ('indice_egreso', models.FloatField(default=0.0)),
                ('indice_titulacion', models.FloatField(default=0.0)),
                ('programa_antiguo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativoantiguo')),
                ('programa_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativonuevo')),
            ],
        ),
        migrations.CreateModel(
            name='TasaTitulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_ingreso', models.IntegerField()),
                ('matricula_ingreso', models.IntegerField(default=0)),
                ('egresados', models.IntegerField(default=0)),
                ('eficiencia_terminal_porcentaje', models.FloatField(default=0.0)),
                ('titulados', models.IntegerField(default=0)),
                ('tasa_titulacion', models.FloatField(default=0.0)),
                ('programa_antiguo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativoantiguo')),
                ('programa_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativonuevo')),
            ],
        ),
        migrations.CreateModel(
            name='TituladosHistoricos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_ingreso', models.IntegerField()),
                ('anio_egreso', models.IntegerField()),
                ('titulados_hombres', models.IntegerField(default=0)),
                ('titulados_mujeres', models.IntegerField(default=0)),
                ('registrados_dgp_h', models.IntegerField(default=0)),
                ('registrados_dgp_m', models.IntegerField(default=0)),
                ('programa_antiguo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativoantiguo')),
                ('programa_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativonuevo')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PA', 'PA'), ('PTC', 'PTC')], max_length=5)),
                ('calificacion_grupal', models.FloatField()),
                ('evaluaciones_realizadas', models.IntegerField(default=0)),
                ('promedio_docente', models.FloatField()),
                ('ciclo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cicloperiodo')),
            ],
            options={
                'unique_together': {('ciclo_periodo', 'profesor')},
            },
        ),
    ]
