# Generated by Django 5.2.4 on 2025-07-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evaluaciondocentecuatrimestre_seguimientolaboral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDocenteAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=20, unique=True)),
                ('promedio', models.FloatField()),
                ('mal', models.IntegerField(default=0)),
                ('regular', models.IntegerField(default=0)),
                ('bien', models.IntegerField(default=0)),
                ('muy_bien', models.IntegerField(default=0)),
                ('excelente', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='EvaluacionDocente',
        ),
    ]
