# Generated by Django 5.2.4 on 2025-07-16 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_evaluaciondocenteanual_delete_evaluaciondocente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluacionDocenteAnual',
            new_name='EvaluacionDocenteConcentrado',
        ),
    ]
