# Generated by Django 5.2 on 2025-08-15 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_evaluaciondocenteanual_evaluaciondocenteconcentrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('TECNICO', 'Técnico'), ('INGENIERO', 'Ingeniero')], max_length=12)),
                ('ref_antiguo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programa_unificado', to='api.programaeducativoantiguo')),
                ('ref_nuevo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programa_unificado', to='api.programaeducativonuevo')),
            ],
        ),
    ]
