# Generated by Django 5.2 on 2025-08-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_programaeducativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programaeducativo',
            name='nombre',
        ),
    ]
