# Generated by Django 5.2 on 2025-08-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_programaeducativo_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programaeducativo',
            old_name='ref_antiguo',
            new_name='antiguo',
        ),
        migrations.RenameField(
            model_name='programaeducativo',
            old_name='ref_nuevo',
            new_name='nuevo',
        ),
        migrations.AddConstraint(
            model_name='programaeducativo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('antiguo__isnull', False), ('nuevo__isnull', True)), models.Q(('antiguo__isnull', True), ('nuevo__isnull', False)), _connector='OR'), name='pe_exatamente_una_referencia'),
        ),
    ]
