# Generated by Django 5.2 on 2025-08-16 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_ref_antiguo_programaeducativo_antiguo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='programaeducativo',
            name='pe_exatamente_una_referencia',
        ),
        migrations.RemoveField(
            model_name='programaeducativo',
            name='antiguo',
        ),
        migrations.RemoveField(
            model_name='programaeducativo',
            name='nuevo',
        ),
    ]
