# Generated by Django 5.1.7 on 2025-08-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_programaeducativo_pe_exatamente_una_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tituladoshistoricos',
            name='semestre',
            field=models.IntegerField(choices=[(5, 'TSU'), (10, 'Ingeniería')], default=5),
        ),
    ]
