# Generated by Django 5.2.4 on 2025-09-09 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20250818_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituladosTSUIng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('TSU', 'TSU'), ('ING', 'Ingeniería')], db_index=True, max_length=3)),
                ('fecha_ingreso', models.DateField(db_index=True)),
                ('fecha_egreso', models.DateField(db_index=True)),
                ('ingreso_hombres', models.IntegerField(default=0)),
                ('ingreso_mujeres', models.IntegerField(default=0)),
                ('egresados_cohorte_h', models.IntegerField(default=0)),
                ('egresados_cohorte_m', models.IntegerField(default=0)),
                ('egresados_rezagados_h', models.IntegerField(default=0)),
                ('egresados_rezagados_m', models.IntegerField(default=0)),
                ('titulados_h', models.IntegerField(default=0)),
                ('titulados_m', models.IntegerField(default=0)),
                ('registrados_dgp_h', models.IntegerField(default=0)),
                ('registrados_dgp_m', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('programa_antiguo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulados_tsu_ing_antiguo', to='api.programaeducativoantiguo')),
                ('programa_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulados_tsu_ing_nuevo', to='api.programaeducativonuevo')),
            ],
            options={
                'verbose_name': 'Titulados TSU/ING',
                'verbose_name_plural': 'Titulados TSU/ING',
                'ordering': ['fecha_ingreso', 'fecha_egreso', 'nivel'],
                'indexes': [models.Index(fields=['nivel', 'fecha_ingreso'], name='api_titulad_nivel_dd5ca3_idx'), models.Index(fields=['nivel', 'fecha_egreso'], name='api_titulad_nivel_dd8327_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('programa_antiguo__isnull', False), ('programa_nuevo__isnull', True)), models.Q(('programa_antiguo__isnull', True), ('programa_nuevo__isnull', False)), _connector='OR'), name='tsui_programa_xor'), models.CheckConstraint(condition=models.Q(('ingreso_hombres__gte', 0), ('ingreso_mujeres__gte', 0), ('egresados_cohorte_h__gte', 0), ('egresados_cohorte_m__gte', 0), ('egresados_rezagados_h__gte', 0), ('egresados_rezagados_m__gte', 0), ('titulados_h__gte', 0), ('titulados_m__gte', 0), ('registrados_dgp_h__gte', 0), ('registrados_dgp_m__gte', 0)), name='tsui_no_negativos'), models.UniqueConstraint(fields=('nivel', 'fecha_ingreso', 'fecha_egreso', 'programa_antiguo', 'programa_nuevo'), name='tsui_unico_gen_prog_nivel')],
            },
        ),
    ]
